// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Microsoft.Kiota.Serialization.Form;
using Microsoft.Kiota.Serialization.Json;
using Microsoft.Kiota.Serialization.Multipart;
using Microsoft.Kiota.Serialization.Text;
using Soenneker.Replicate.OpenApiClient.Account;
using Soenneker.Replicate.OpenApiClient.Collections;
using Soenneker.Replicate.OpenApiClient.Deployments;
using Soenneker.Replicate.OpenApiClient.Files;
using Soenneker.Replicate.OpenApiClient.Hardware;
using Soenneker.Replicate.OpenApiClient.ModelsRequests;
using Soenneker.Replicate.OpenApiClient.Predictions;
using Soenneker.Replicate.OpenApiClient.Search;
using Soenneker.Replicate.OpenApiClient.Trainings;
using Soenneker.Replicate.OpenApiClient.Webhooks;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Replicate.OpenApiClient
{
    /// <summary>
    /// The main entry point of the SDK, exposes the configuration and the fluent API.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ReplicateOpenApiClient : BaseRequestBuilder
    {
        /// <summary>The account property</summary>
        public global::Soenneker.Replicate.OpenApiClient.Account.AccountRequestBuilder Account
        {
            get => new global::Soenneker.Replicate.OpenApiClient.Account.AccountRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The collections property</summary>
        public global::Soenneker.Replicate.OpenApiClient.Collections.CollectionsRequestBuilder Collections
        {
            get => new global::Soenneker.Replicate.OpenApiClient.Collections.CollectionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deployments property</summary>
        public global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsRequestBuilder Deployments
        {
            get => new global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The files property</summary>
        public global::Soenneker.Replicate.OpenApiClient.Files.FilesRequestBuilder Files
        {
            get => new global::Soenneker.Replicate.OpenApiClient.Files.FilesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The hardware property</summary>
        public global::Soenneker.Replicate.OpenApiClient.Hardware.HardwareRequestBuilder Hardware
        {
            get => new global::Soenneker.Replicate.OpenApiClient.Hardware.HardwareRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The models property</summary>
        public global::Soenneker.Replicate.OpenApiClient.ModelsRequests.ModelsRequestBuilder Models
        {
            get => new global::Soenneker.Replicate.OpenApiClient.ModelsRequests.ModelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The predictions property</summary>
        public global::Soenneker.Replicate.OpenApiClient.Predictions.PredictionsRequestBuilder Predictions
        {
            get => new global::Soenneker.Replicate.OpenApiClient.Predictions.PredictionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The search property</summary>
        public global::Soenneker.Replicate.OpenApiClient.Search.SearchRequestBuilder Search
        {
            get => new global::Soenneker.Replicate.OpenApiClient.Search.SearchRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The trainings property</summary>
        public global::Soenneker.Replicate.OpenApiClient.Trainings.TrainingsRequestBuilder Trainings
        {
            get => new global::Soenneker.Replicate.OpenApiClient.Trainings.TrainingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Soenneker.Replicate.OpenApiClient.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Soenneker.Replicate.OpenApiClient.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.ReplicateOpenApiClient"/> and sets the default values.
        /// </summary>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ReplicateOpenApiClient(IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}", new Dictionary<string, object>())
        {
            ApiClientBuilder.RegisterDefaultSerializer<JsonSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<TextSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<FormSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultSerializer<MultipartSerializationWriterFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<JsonParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<TextParseNodeFactory>();
            ApiClientBuilder.RegisterDefaultDeserializer<FormParseNodeFactory>();
            if (string.IsNullOrEmpty(RequestAdapter.BaseUrl))
            {
                RequestAdapter.BaseUrl = "https://api.replicate.com/v1";
            }
            PathParameters.TryAdd("baseurl", RequestAdapter.BaseUrl);
        }
    }
}
#pragma warning restore CS0618
