// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Replicate.OpenApiClient.Collections.Item;
using Soenneker.Replicate.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Replicate.OpenApiClient.Collections
{
    /// <summary>
    /// Builds and executes requests for operations under \collections
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CollectionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Replicate.OpenApiClient.collections.item collection</summary>
        /// <param name="position">The slug of the collection, like `super-resolution` or `image-restoration`. See [replicate.com/collections](https://replicate.com/collections).</param>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Collections.Item.WithCollection_slugItemRequestBuilder"/></returns>
        public global::Soenneker.Replicate.OpenApiClient.Collections.Item.WithCollection_slugItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("collection_slug", position);
                return new global::Soenneker.Replicate.OpenApiClient.Collections.Item.WithCollection_slugItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Collections.CollectionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CollectionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/collections", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Collections.CollectionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CollectionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/collections", rawUrl)
        {
        }
        /// <summary>
        /// Example cURL request:```consolecurl -s \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  https://api.replicate.com/v1/collections```The response will be a paginated JSON list of collection objects:```json{  &quot;next&quot;: &quot;null&quot;,  &quot;previous&quot;: null,  &quot;results&quot;: [    {      &quot;name&quot;: &quot;Super resolution&quot;,      &quot;slug&quot;: &quot;super-resolution&quot;,      &quot;description&quot;: &quot;Upscaling models that create high-quality images from low-quality images.&quot;    }  ]}```
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_paginated_collection_response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_paginated_collection_response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_paginated_collection_response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_paginated_collection_response>(requestInfo, global::Soenneker.Replicate.OpenApiClient.Models.Schemas_paginated_collection_response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Example cURL request:```consolecurl -s \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  https://api.replicate.com/v1/collections```The response will be a paginated JSON list of collection objects:```json{  &quot;next&quot;: &quot;null&quot;,  &quot;previous&quot;: null,  &quot;results&quot;: [    {      &quot;name&quot;: &quot;Super resolution&quot;,      &quot;slug&quot;: &quot;super-resolution&quot;,      &quot;description&quot;: &quot;Upscaling models that create high-quality images from low-quality images.&quot;    }  ]}```
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Collections.CollectionsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Replicate.OpenApiClient.Collections.CollectionsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Replicate.OpenApiClient.Collections.CollectionsRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
