// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Replicate.OpenApiClient.Deployments.Item;
using Soenneker.Replicate.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Replicate.OpenApiClient.Deployments
{
    /// <summary>
    /// Builds and executes requests for operations under \deployments
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DeploymentsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Replicate.OpenApiClient.deployments.item collection</summary>
        /// <param name="position">The name of the user or organization that owns the deployment.</param>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Deployments.Item.WithDeployment_ownerItemRequestBuilder"/></returns>
        public global::Soenneker.Replicate.OpenApiClient.Deployments.Item.WithDeployment_ownerItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("deployment_owner", position);
                return new global::Soenneker.Replicate.OpenApiClient.Deployments.Item.WithDeployment_ownerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeploymentsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/deployments", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DeploymentsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/deployments", rawUrl)
        {
        }
        /// <summary>
        /// Get a list of deployments associated with the current account, including the latest release configuration for each deployment.Example cURL request:```consolecurl -s \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  https://api.replicate.com/v1/deployments```The response will be a paginated JSON array of deployment objects, sorted with the most recent deployment first:```json{  &quot;next&quot;: &quot;http://api.replicate.com/v1/deployments?cursor=cD0yMDIzLTA2LTA2KzIzJTNBNDAlM0EwOC45NjMwMDAlMkIwMCUzQTAw&quot;,  &quot;previous&quot;: null,  &quot;results&quot;: [    {      &quot;owner&quot;: &quot;replicate&quot;,      &quot;name&quot;: &quot;my-app-image-generator&quot;,      &quot;current_release&quot;: {        &quot;number&quot;: 1,        &quot;model&quot;: &quot;stability-ai/sdxl&quot;,        &quot;version&quot;: &quot;da77bc59ee60423279fd632efb4795ab731d9e3ca9705ef3341091fb989b7eaf&quot;,        &quot;created_at&quot;: &quot;2024-02-15T16:32:57.018467Z&quot;,        &quot;created_by&quot;: {          &quot;type&quot;: &quot;organization&quot;,          &quot;username&quot;: &quot;acme&quot;,          &quot;name&quot;: &quot;Acme Corp, Inc.&quot;,          &quot;avatar_url&quot;: &quot;https://cdn.replicate.com/avatars/acme.png&quot;,          &quot;github_url&quot;: &quot;https://github.com/acme&quot;        },        &quot;configuration&quot;: {          &quot;hardware&quot;: &quot;gpu-t4&quot;,          &quot;min_instances&quot;: 1,          &quot;max_instances&quot;: 5        }      }    }  ]}```
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsGetResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsGetResponse?> GetAsDeploymentsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsGetResponse> GetAsDeploymentsGetResponseAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsGetResponse>(requestInfo, global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsGetResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a list of deployments associated with the current account, including the latest release configuration for each deployment.Example cURL request:```consolecurl -s \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  https://api.replicate.com/v1/deployments```The response will be a paginated JSON array of deployment objects, sorted with the most recent deployment first:```json{  &quot;next&quot;: &quot;http://api.replicate.com/v1/deployments?cursor=cD0yMDIzLTA2LTA2KzIzJTNBNDAlM0EwOC45NjMwMDAlMkIwMCUzQTAw&quot;,  &quot;previous&quot;: null,  &quot;results&quot;: [    {      &quot;owner&quot;: &quot;replicate&quot;,      &quot;name&quot;: &quot;my-app-image-generator&quot;,      &quot;current_release&quot;: {        &quot;number&quot;: 1,        &quot;model&quot;: &quot;stability-ai/sdxl&quot;,        &quot;version&quot;: &quot;da77bc59ee60423279fd632efb4795ab731d9e3ca9705ef3341091fb989b7eaf&quot;,        &quot;created_at&quot;: &quot;2024-02-15T16:32:57.018467Z&quot;,        &quot;created_by&quot;: {          &quot;type&quot;: &quot;organization&quot;,          &quot;username&quot;: &quot;acme&quot;,          &quot;name&quot;: &quot;Acme Corp, Inc.&quot;,          &quot;avatar_url&quot;: &quot;https://cdn.replicate.com/avatars/acme.png&quot;,          &quot;github_url&quot;: &quot;https://github.com/acme&quot;        },        &quot;configuration&quot;: {          &quot;hardware&quot;: &quot;gpu-t4&quot;,          &quot;min_instances&quot;: 1,          &quot;max_instances&quot;: 5        }      }    }  ]}```
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("This method is obsolete. Use GetAsDeploymentsGetResponseAsync instead.")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsResponse>(requestInfo, global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsResponse.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a new deployment:Example cURL request:```consolecurl -s \  -X POST \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  -H &quot;Content-Type: application/json&quot; \  -d &apos;{        &quot;name&quot;: &quot;my-app-image-generator&quot;,        &quot;model&quot;: &quot;stability-ai/sdxl&quot;,        &quot;version&quot;: &quot;da77bc59ee60423279fd632efb4795ab731d9e3ca9705ef3341091fb989b7eaf&quot;,        &quot;hardware&quot;: &quot;gpu-t4&quot;,        &quot;min_instances&quot;: 0,        &quot;max_instances&quot;: 3      }&apos; \  https://api.replicate.com/v1/deployments```The response will be a JSON object describing the deployment:```json{  &quot;owner&quot;: &quot;acme&quot;,  &quot;name&quot;: &quot;my-app-image-generator&quot;,  &quot;current_release&quot;: {    &quot;number&quot;: 1,    &quot;model&quot;: &quot;stability-ai/sdxl&quot;,    &quot;version&quot;: &quot;da77bc59ee60423279fd632efb4795ab731d9e3ca9705ef3341091fb989b7eaf&quot;,    &quot;created_at&quot;: &quot;2024-02-15T16:32:57.018467Z&quot;,    &quot;created_by&quot;: {      &quot;type&quot;: &quot;organization&quot;,      &quot;username&quot;: &quot;acme&quot;,      &quot;name&quot;: &quot;Acme Corp, Inc.&quot;,      &quot;avatar_url&quot;: &quot;https://cdn.replicate.com/avatars/acme.png&quot;,      &quot;github_url&quot;: &quot;https://github.com/acme&quot;    },    &quot;configuration&quot;: {      &quot;hardware&quot;: &quot;gpu-t4&quot;,      &quot;min_instances&quot;: 1,      &quot;max_instances&quot;: 5    }  }}```
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_deployment_response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_deployment_response?> PostAsync(global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_deployment_response> PostAsync(global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_deployment_response>(requestInfo, global::Soenneker.Replicate.OpenApiClient.Models.Schemas_deployment_response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a list of deployments associated with the current account, including the latest release configuration for each deployment.Example cURL request:```consolecurl -s \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  https://api.replicate.com/v1/deployments```The response will be a paginated JSON array of deployment objects, sorted with the most recent deployment first:```json{  &quot;next&quot;: &quot;http://api.replicate.com/v1/deployments?cursor=cD0yMDIzLTA2LTA2KzIzJTNBNDAlM0EwOC45NjMwMDAlMkIwMCUzQTAw&quot;,  &quot;previous&quot;: null,  &quot;results&quot;: [    {      &quot;owner&quot;: &quot;replicate&quot;,      &quot;name&quot;: &quot;my-app-image-generator&quot;,      &quot;current_release&quot;: {        &quot;number&quot;: 1,        &quot;model&quot;: &quot;stability-ai/sdxl&quot;,        &quot;version&quot;: &quot;da77bc59ee60423279fd632efb4795ab731d9e3ca9705ef3341091fb989b7eaf&quot;,        &quot;created_at&quot;: &quot;2024-02-15T16:32:57.018467Z&quot;,        &quot;created_by&quot;: {          &quot;type&quot;: &quot;organization&quot;,          &quot;username&quot;: &quot;acme&quot;,          &quot;name&quot;: &quot;Acme Corp, Inc.&quot;,          &quot;avatar_url&quot;: &quot;https://cdn.replicate.com/avatars/acme.png&quot;,          &quot;github_url&quot;: &quot;https://github.com/acme&quot;        },        &quot;configuration&quot;: {          &quot;hardware&quot;: &quot;gpu-t4&quot;,          &quot;min_instances&quot;: 1,          &quot;max_instances&quot;: 5        }      }    }  ]}```
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a new deployment:Example cURL request:```consolecurl -s \  -X POST \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  -H &quot;Content-Type: application/json&quot; \  -d &apos;{        &quot;name&quot;: &quot;my-app-image-generator&quot;,        &quot;model&quot;: &quot;stability-ai/sdxl&quot;,        &quot;version&quot;: &quot;da77bc59ee60423279fd632efb4795ab731d9e3ca9705ef3341091fb989b7eaf&quot;,        &quot;hardware&quot;: &quot;gpu-t4&quot;,        &quot;min_instances&quot;: 0,        &quot;max_instances&quot;: 3      }&apos; \  https://api.replicate.com/v1/deployments```The response will be a JSON object describing the deployment:```json{  &quot;owner&quot;: &quot;acme&quot;,  &quot;name&quot;: &quot;my-app-image-generator&quot;,  &quot;current_release&quot;: {    &quot;number&quot;: 1,    &quot;model&quot;: &quot;stability-ai/sdxl&quot;,    &quot;version&quot;: &quot;da77bc59ee60423279fd632efb4795ab731d9e3ca9705ef3341091fb989b7eaf&quot;,    &quot;created_at&quot;: &quot;2024-02-15T16:32:57.018467Z&quot;,    &quot;created_by&quot;: {      &quot;type&quot;: &quot;organization&quot;,      &quot;username&quot;: &quot;acme&quot;,      &quot;name&quot;: &quot;Acme Corp, Inc.&quot;,      &quot;avatar_url&quot;: &quot;https://cdn.replicate.com/avatars/acme.png&quot;,      &quot;github_url&quot;: &quot;https://github.com/acme&quot;    },    &quot;configuration&quot;: {      &quot;hardware&quot;: &quot;gpu-t4&quot;,      &quot;min_instances&quot;: 1,      &quot;max_instances&quot;: 5    }  }}```
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Replicate.OpenApiClient.Deployments.DeploymentsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DeploymentsRequestBuilderGetRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
        /// <summary>
        /// Configuration for the request such as headers, query parameters, and middleware options.
        /// </summary>
        [Obsolete("This class is deprecated. Please use the generic RequestConfiguration class generated by the generator.")]
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DeploymentsRequestBuilderPostRequestConfiguration : RequestConfiguration<DefaultQueryParameters>
        {
        }
    }
}
#pragma warning restore CS0618
