// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Replicate.OpenApiClient.Deployments.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Replicate.OpenApiClient.Deployments.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \deployments\{deploymentOwner}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDeploymentOwnerItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Replicate.OpenApiClient.deployments.item.item collection</summary>
        /// <param name="position">The name of the deployment.</param>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.WithDeploymentNameItemRequestBuilder"/></returns>
        public global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.WithDeploymentNameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("deploymentName", position);
                return new global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.WithDeploymentNameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Deployments.Item.WithDeploymentOwnerItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDeploymentOwnerItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/deployments/{deploymentOwner}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Deployments.Item.WithDeploymentOwnerItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDeploymentOwnerItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/deployments/{deploymentOwner}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
