// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Replicate.OpenApiClient.Deployments.Item.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Replicate.OpenApiClient.Deployments.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \deployments\{deployment_owner}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDeployment_ownerItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Replicate.OpenApiClient.deployments.item.item collection</summary>
        /// <param name="position">The name of the deployment.</param>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.WithDeployment_nameItemRequestBuilder"/></returns>
        public global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.WithDeployment_nameItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("deployment_name", position);
                return new global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.WithDeployment_nameItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Deployments.Item.WithDeployment_ownerItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDeployment_ownerItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/deployments/{deployment_owner}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Deployments.Item.WithDeployment_ownerItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDeployment_ownerItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/deployments/{deployment_owner}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
