// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Replicate.OpenApiClient.ModelsRequests
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetSort_byQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "model_created_at")]
        #pragma warning disable CS1591
        Model_created_at,
        #pragma warning restore CS1591
        [EnumMember(Value = "latest_version_created_at")]
        #pragma warning disable CS1591
        Latest_version_created_at,
        #pragma warning restore CS1591
    }
}
