// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Replicate.OpenApiClient.Models;
using Soenneker.Replicate.OpenApiClient.ModelsRequests.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Replicate.OpenApiClient.ModelsRequests
{
    /// <summary>
    /// Builds and executes requests for operations under \models
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ModelsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Replicate.OpenApiClient.modelsRequests.item collection</summary>
        /// <param name="position">The name of the user or organization that owns the model.</param>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.ModelsRequests.Item.WithModel_ownerItemRequestBuilder"/></returns>
        public global::Soenneker.Replicate.OpenApiClient.ModelsRequests.Item.WithModel_ownerItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("model_owner", position);
                return new global::Soenneker.Replicate.OpenApiClient.ModelsRequests.Item.WithModel_ownerItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.ModelsRequests.ModelsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ModelsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/models{?sort_by*,sort_direction*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.ModelsRequests.ModelsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ModelsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/models{?sort_by*,sort_direction*}", rawUrl)
        {
        }
        /// <summary>
        /// Get a paginated list of public models.Example cURL request:```consolecurl -s \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  https://api.replicate.com/v1/models```The response will be a pagination object containing a list of model objects.See the [`models.get`](#models.get) docs for more details about the model object.## SortingYou can sort the results using the `sort_by` and `sort_direction` query parameters.For example, to get the most recently created models:```consolecurl -s \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  &quot;https://api.replicate.com/v1/models?sort_by=model_created_at&amp;sort_direction=desc&quot;```Available sorting options:- `model_created_at`: Sort by when the model was first created- `latest_version_created_at`: Sort by when the model&apos;s latest version was created (default)Sort direction can be `asc` (ascending) or `desc` (descending, default).
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_paginated_model_response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_paginated_model_response?> GetAsync(Action<RequestConfiguration<global::Soenneker.Replicate.OpenApiClient.ModelsRequests.ModelsRequestBuilder.ModelsRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_paginated_model_response> GetAsync(Action<RequestConfiguration<global::Soenneker.Replicate.OpenApiClient.ModelsRequests.ModelsRequestBuilder.ModelsRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_paginated_model_response>(requestInfo, global::Soenneker.Replicate.OpenApiClient.Models.Schemas_paginated_model_response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Create a model.Example cURL request:```consolecurl -s -X POST \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  -H &apos;Content-Type: application/json&apos; \  -d &apos;{&quot;owner&quot;: &quot;alice&quot;, &quot;name&quot;: &quot;hot-dog-detector&quot;, &quot;description&quot;: &quot;Detect hot dogs in images&quot;, &quot;visibility&quot;: &quot;public&quot;, &quot;hardware&quot;: &quot;cpu&quot;}&apos; \  https://api.replicate.com/v1/models```The response will be a model object in the following format:```json{  &quot;url&quot;: &quot;https://replicate.com/alice/hot-dog-detector&quot;,  &quot;owner&quot;: &quot;alice&quot;,  &quot;name&quot;: &quot;hot-dog-detector&quot;,  &quot;description&quot;: &quot;Detect hot dogs in images&quot;,  &quot;visibility&quot;: &quot;public&quot;,  &quot;github_url&quot;: null,  &quot;paper_url&quot;: null,  &quot;license_url&quot;: null,  &quot;run_count&quot;: 0,  &quot;cover_image_url&quot;: null,  &quot;default_example&quot;: null,  &quot;latest_version&quot;: null,}```Note that there is a limit of 1,000 models per account. For most purposes, we recommend using a single model and pushing new [versions](https://replicate.com/docs/how-does-replicate-work#versions) of the model as you make changes to it.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response?> PostAsync(global::Soenneker.Replicate.OpenApiClient.ModelsRequests.ModelsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response> PostAsync(global::Soenneker.Replicate.OpenApiClient.ModelsRequests.ModelsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response>(requestInfo, global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get a paginated list of public models.Example cURL request:```consolecurl -s \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  https://api.replicate.com/v1/models```The response will be a pagination object containing a list of model objects.See the [`models.get`](#models.get) docs for more details about the model object.## SortingYou can sort the results using the `sort_by` and `sort_direction` query parameters.For example, to get the most recently created models:```consolecurl -s \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  &quot;https://api.replicate.com/v1/models?sort_by=model_created_at&amp;sort_direction=desc&quot;```Available sorting options:- `model_created_at`: Sort by when the model was first created- `latest_version_created_at`: Sort by when the model&apos;s latest version was created (default)Sort direction can be `asc` (ascending) or `desc` (descending, default).
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Replicate.OpenApiClient.ModelsRequests.ModelsRequestBuilder.ModelsRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Replicate.OpenApiClient.ModelsRequests.ModelsRequestBuilder.ModelsRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Create a model.Example cURL request:```consolecurl -s -X POST \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  -H &apos;Content-Type: application/json&apos; \  -d &apos;{&quot;owner&quot;: &quot;alice&quot;, &quot;name&quot;: &quot;hot-dog-detector&quot;, &quot;description&quot;: &quot;Detect hot dogs in images&quot;, &quot;visibility&quot;: &quot;public&quot;, &quot;hardware&quot;: &quot;cpu&quot;}&apos; \  https://api.replicate.com/v1/models```The response will be a model object in the following format:```json{  &quot;url&quot;: &quot;https://replicate.com/alice/hot-dog-detector&quot;,  &quot;owner&quot;: &quot;alice&quot;,  &quot;name&quot;: &quot;hot-dog-detector&quot;,  &quot;description&quot;: &quot;Detect hot dogs in images&quot;,  &quot;visibility&quot;: &quot;public&quot;,  &quot;github_url&quot;: null,  &quot;paper_url&quot;: null,  &quot;license_url&quot;: null,  &quot;run_count&quot;: 0,  &quot;cover_image_url&quot;: null,  &quot;default_example&quot;: null,  &quot;latest_version&quot;: null,}```Note that there is a limit of 1,000 models per account. For most purposes, we recommend using a single model and pushing new [versions](https://replicate.com/docs/how-does-replicate-work#versions) of the model as you make changes to it.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Replicate.OpenApiClient.ModelsRequests.ModelsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Replicate.OpenApiClient.ModelsRequests.ModelsPostRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.ModelsRequests.ModelsRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Replicate.OpenApiClient.ModelsRequests.ModelsRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Replicate.OpenApiClient.ModelsRequests.ModelsRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// Get a paginated list of public models.Example cURL request:```consolecurl -s \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  https://api.replicate.com/v1/models```The response will be a pagination object containing a list of model objects.See the [`models.get`](#models.get) docs for more details about the model object.## SortingYou can sort the results using the `sort_by` and `sort_direction` query parameters.For example, to get the most recently created models:```consolecurl -s \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  &quot;https://api.replicate.com/v1/models?sort_by=model_created_at&amp;sort_direction=desc&quot;```Available sorting options:- `model_created_at`: Sort by when the model was first created- `latest_version_created_at`: Sort by when the model&apos;s latest version was created (default)Sort direction can be `asc` (ascending) or `desc` (descending, default).
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class ModelsRequestBuilderGetQueryParameters 
        {
            /// <summary>Field to sort models by. Defaults to `latest_version_created_at`.</summary>
            [QueryParameter("sort_by")]
            public global::Soenneker.Replicate.OpenApiClient.ModelsRequests.GetSort_byQueryParameterType? SortBy { get; set; }
            /// <summary>Sort direction. Defaults to `desc` (descending, newest first).</summary>
            [QueryParameter("sort_direction")]
            public global::Soenneker.Replicate.OpenApiClient.ModelsRequests.GetSort_directionQueryParameterType? SortDirection { get; set; }
        }
    }
}
#pragma warning restore CS0618
