// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Replicate.OpenApiClient.Webhooks.Default.Secret;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Replicate.OpenApiClient.Webhooks.Default
{
    /// <summary>
    /// Builds and executes requests for operations under \webhooks\default
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DefaultRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The secret property</summary>
        public global::Soenneker.Replicate.OpenApiClient.Webhooks.Default.Secret.SecretRequestBuilder Secret
        {
            get => new global::Soenneker.Replicate.OpenApiClient.Webhooks.Default.Secret.SecretRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Webhooks.Default.DefaultRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DefaultRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/webhooks/default", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Webhooks.Default.DefaultRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DefaultRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/webhooks/default", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
