// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.Predictions;
using Soenneker.Replicate.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Replicate.OpenApiClient.Deployments.Item.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \deployments\{deployment_owner}\{deployment_name}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDeployment_nameItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The predictions property</summary>
        public global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.Predictions.PredictionsRequestBuilder Predictions
        {
            get => new global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.Predictions.PredictionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.WithDeployment_nameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDeployment_nameItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/deployments/{deployment_owner}/{deployment_name}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.WithDeployment_nameItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDeployment_nameItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/deployments/{deployment_owner}/{deployment_name}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a deploymentDeployment deletion has some restrictions:- You can only delete deployments that have been offline and unused for at least 15 minutes.Example cURL request:```commandcurl -s -X DELETE \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  https://api.replicate.com/v1/deployments/acme/my-app-image-generator```The response will be an empty 204, indicating the deployment has been deleted.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Get information about a deployment by name including the current release.Example cURL request:```consolecurl -s \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  https://api.replicate.com/v1/deployments/replicate/my-app-image-generator```The response will be a JSON object describing the deployment:```json{  &quot;owner&quot;: &quot;acme&quot;,  &quot;name&quot;: &quot;my-app-image-generator&quot;,  &quot;current_release&quot;: {    &quot;number&quot;: 1,    &quot;model&quot;: &quot;stability-ai/sdxl&quot;,    &quot;version&quot;: &quot;da77bc59ee60423279fd632efb4795ab731d9e3ca9705ef3341091fb989b7eaf&quot;,    &quot;created_at&quot;: &quot;2024-02-15T16:32:57.018467Z&quot;,    &quot;created_by&quot;: {      &quot;type&quot;: &quot;organization&quot;,      &quot;username&quot;: &quot;acme&quot;,      &quot;name&quot;: &quot;Acme Corp, Inc.&quot;,      &quot;avatar_url&quot;: &quot;https://cdn.replicate.com/avatars/acme.png&quot;,      &quot;github_url&quot;: &quot;https://github.com/acme&quot;    },    &quot;configuration&quot;: {      &quot;hardware&quot;: &quot;gpu-t4&quot;,      &quot;min_instances&quot;: 1,      &quot;max_instances&quot;: 5    }  }}```
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_deployment_response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_deployment_response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_deployment_response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_deployment_response>(requestInfo, global::Soenneker.Replicate.OpenApiClient.Models.Schemas_deployment_response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Update properties of an existing deployment, including hardware, min/max instances, and the deployment&apos;s underlying model [version](https://replicate.com/docs/how-does-replicate-work#versions).Example cURL request:```consolecurl -s \  -X PATCH \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  -H &quot;Content-Type: application/json&quot; \  -d &apos;{&quot;min_instances&quot;: 3, &quot;max_instances&quot;: 10}&apos; \  https://api.replicate.com/v1/deployments/acme/my-app-image-generator```The response will be a JSON object describing the deployment:```json{  &quot;owner&quot;: &quot;acme&quot;,  &quot;name&quot;: &quot;my-app-image-generator&quot;,  &quot;current_release&quot;: {    &quot;number&quot;: 2,    &quot;model&quot;: &quot;stability-ai/sdxl&quot;,    &quot;version&quot;: &quot;da77bc59ee60423279fd632efb4795ab731d9e3ca9705ef3341091fb989b7eaf&quot;,    &quot;created_at&quot;: &quot;2024-02-15T16:32:57.018467Z&quot;,    &quot;created_by&quot;: {      &quot;type&quot;: &quot;organization&quot;,      &quot;username&quot;: &quot;acme&quot;,      &quot;name&quot;: &quot;Acme Corp, Inc.&quot;,      &quot;avatar_url&quot;: &quot;https://cdn.replicate.com/avatars/acme.png&quot;,      &quot;github_url&quot;: &quot;https://github.com/acme&quot;    },    &quot;configuration&quot;: {      &quot;hardware&quot;: &quot;gpu-t4&quot;,      &quot;min_instances&quot;: 3,      &quot;max_instances&quot;: 10    }  }}```Updating any deployment properties will increment the `number` field of the `current_release`.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_deployment_response"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_deployment_response?> PatchAsync(global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.WithDeployment_namePatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_deployment_response> PatchAsync(global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.WithDeployment_namePatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_deployment_response>(requestInfo, global::Soenneker.Replicate.OpenApiClient.Models.Schemas_deployment_response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a deploymentDeployment deletion has some restrictions:- You can only delete deployments that have been offline and unused for at least 15 minutes.Example cURL request:```commandcurl -s -X DELETE \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  https://api.replicate.com/v1/deployments/acme/my-app-image-generator```The response will be an empty 204, indicating the deployment has been deleted.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Get information about a deployment by name including the current release.Example cURL request:```consolecurl -s \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  https://api.replicate.com/v1/deployments/replicate/my-app-image-generator```The response will be a JSON object describing the deployment:```json{  &quot;owner&quot;: &quot;acme&quot;,  &quot;name&quot;: &quot;my-app-image-generator&quot;,  &quot;current_release&quot;: {    &quot;number&quot;: 1,    &quot;model&quot;: &quot;stability-ai/sdxl&quot;,    &quot;version&quot;: &quot;da77bc59ee60423279fd632efb4795ab731d9e3ca9705ef3341091fb989b7eaf&quot;,    &quot;created_at&quot;: &quot;2024-02-15T16:32:57.018467Z&quot;,    &quot;created_by&quot;: {      &quot;type&quot;: &quot;organization&quot;,      &quot;username&quot;: &quot;acme&quot;,      &quot;name&quot;: &quot;Acme Corp, Inc.&quot;,      &quot;avatar_url&quot;: &quot;https://cdn.replicate.com/avatars/acme.png&quot;,      &quot;github_url&quot;: &quot;https://github.com/acme&quot;    },    &quot;configuration&quot;: {      &quot;hardware&quot;: &quot;gpu-t4&quot;,      &quot;min_instances&quot;: 1,      &quot;max_instances&quot;: 5    }  }}```
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Update properties of an existing deployment, including hardware, min/max instances, and the deployment&apos;s underlying model [version](https://replicate.com/docs/how-does-replicate-work#versions).Example cURL request:```consolecurl -s \  -X PATCH \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  -H &quot;Content-Type: application/json&quot; \  -d &apos;{&quot;min_instances&quot;: 3, &quot;max_instances&quot;: 10}&apos; \  https://api.replicate.com/v1/deployments/acme/my-app-image-generator```The response will be a JSON object describing the deployment:```json{  &quot;owner&quot;: &quot;acme&quot;,  &quot;name&quot;: &quot;my-app-image-generator&quot;,  &quot;current_release&quot;: {    &quot;number&quot;: 2,    &quot;model&quot;: &quot;stability-ai/sdxl&quot;,    &quot;version&quot;: &quot;da77bc59ee60423279fd632efb4795ab731d9e3ca9705ef3341091fb989b7eaf&quot;,    &quot;created_at&quot;: &quot;2024-02-15T16:32:57.018467Z&quot;,    &quot;created_by&quot;: {      &quot;type&quot;: &quot;organization&quot;,      &quot;username&quot;: &quot;acme&quot;,      &quot;name&quot;: &quot;Acme Corp, Inc.&quot;,      &quot;avatar_url&quot;: &quot;https://cdn.replicate.com/avatars/acme.png&quot;,      &quot;github_url&quot;: &quot;https://github.com/acme&quot;    },    &quot;configuration&quot;: {      &quot;hardware&quot;: &quot;gpu-t4&quot;,      &quot;min_instances&quot;: 3,      &quot;max_instances&quot;: 10    }  }}```Updating any deployment properties will increment the `number` field of the `current_release`.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.WithDeployment_namePatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.WithDeployment_namePatchRequestBody body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.WithDeployment_nameItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.WithDeployment_nameItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Replicate.OpenApiClient.Deployments.Item.Item.WithDeployment_nameItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
