// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Replicate.OpenApiClient.Models
{
    /// <summary>Whether the model should be public or private. A public model can be viewed and run by anyone, whereas a private model can be viewed and run only by the user or organization members that own the model.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ModelsCreateRequestVisibility
    {
        [EnumMember(Value = "public")]
        #pragma warning disable CS1591
        PublicValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "private")]
        #pragma warning disable CS1591
        PrivateValue,
        #pragma warning restore CS1591
    }
}
