// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Replicate.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ModelsListSortByParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "model_created_at")]
        #pragma warning disable CS1591
        ModelCreatedAt,
        #pragma warning restore CS1591
        [EnumMember(Value = "latest_version_created_at")]
        #pragma warning disable CS1591
        LatestVersionCreatedAt,
        #pragma warning restore CS1591
    }
}
