// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Replicate.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Schemas_training_request : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A string representing the desired model to push to in the format `{destination_model_owner}/{destination_model_name}`. This should be an existing model owned by the user or organization making the API request. If the destination is invalid, the server will return an appropriate 4XX response.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Destination { get; set; }
#nullable restore
#else
        public string Destination { get; set; }
#endif
        /// <summary>An object containing inputs to the Cog model&apos;s `train()` function.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_request_input? Input { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_request_input Input { get; set; }
#endif
        /// <summary>An HTTPS URL for receiving a webhook when the training completes. The webhook will be a POST request where the request body is the same as the response body of the [get training](#trainings.get) operation. If there are network problems, we will retry the webhook a few times, so make sure it can be safely called more than once. Replicate will not follow redirects when sending webhook requests to your service, so be sure to specify a URL that will resolve without redirecting.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Webhook { get; set; }
#nullable restore
#else
        public string Webhook { get; set; }
#endif
        /// <summary>By default, we will send requests to your webhook URL whenever there are new outputs or the training has finished. You can change which events trigger webhook requests by specifying `webhook_events_filter` in the training request:- `start`: immediately on training start- `output`: each time a training generates an output (note that trainings can generate multiple outputs)- `logs`: each time log output is generated by a training- `completed`: when the training reaches a terminal state (succeeded/canceled/failed)For example, if you only wanted requests to be sent at the start and end of the training, you would provide:```json{  &quot;destination&quot;: &quot;my-organization/my-model&quot;,  &quot;input&quot;: {    &quot;text&quot;: &quot;Alice&quot;  },  &quot;webhook&quot;: &quot;https://example.com/my-webhook&quot;,  &quot;webhook_events_filter&quot;: [&quot;start&quot;, &quot;completed&quot;]}```Requests for event types `output` and `logs` will be sent at most once every 500ms. If you request `start` and `completed` webhooks, then they&apos;ll always be sent regardless of throttling.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_request_webhook_events_filter?>? WebhookEventsFilter { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_request_webhook_events_filter?> WebhookEventsFilter { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_request"/> and sets the default values.
        /// </summary>
        public Schemas_training_request()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_request"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_request CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_request();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "destination", n => { Destination = n.GetStringValue(); } },
                { "input", n => { Input = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_request_input>(global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_request_input.CreateFromDiscriminatorValue); } },
                { "webhook", n => { Webhook = n.GetStringValue(); } },
                { "webhook_events_filter", n => { WebhookEventsFilter = n.GetCollectionOfEnumValues<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_request_webhook_events_filter>()?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("destination", Destination);
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_request_input>("input", Input);
            writer.WriteStringValue("webhook", Webhook);
            writer.WriteCollectionOfEnumValues<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_request_webhook_events_filter>("webhook_events_filter", WebhookEventsFilter);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
