// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Replicate.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Schemas_search_response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Array of collections that match the search query</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_collection_response>? Collections { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_collection_response> Collections { get; set; }
#endif
        /// <summary>Array of models that match the search query, each containing model data and extra metadata</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_response_models>? Models { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_response_models> Models { get; set; }
#endif
        /// <summary>Array of Replicate documentation pages that match the search query</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_page_response>? Pages { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_page_response> Pages { get; set; }
#endif
        /// <summary>The search term that was evaluated</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Query { get; set; }
#nullable restore
#else
        public string Query { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_response"/> and sets the default values.
        /// </summary>
        public Schemas_search_response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "collections", n => { Collections = n.GetCollectionOfObjectValues<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_collection_response>(global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_collection_response.CreateFromDiscriminatorValue)?.AsList(); } },
                { "models", n => { Models = n.GetCollectionOfObjectValues<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_response_models>(global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_response_models.CreateFromDiscriminatorValue)?.AsList(); } },
                { "pages", n => { Pages = n.GetCollectionOfObjectValues<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_page_response>(global::Soenneker.Replicate.OpenApiClient.Models.Schemas_page_response.CreateFromDiscriminatorValue)?.AsList(); } },
                { "query", n => { Query = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_collection_response>("collections", Collections);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_response_models>("models", Models);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_page_response>("pages", Pages);
            writer.WriteStringValue("query", Query);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
