// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Replicate.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Schemas_search_response_models : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The metadata property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_model_metadata_response? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_model_metadata_response Metadata { get; set; }
#endif
        /// <summary>The model property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response? Model { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response Model { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_response_models"/> and sets the default values.
        /// </summary>
        public Schemas_search_response_models()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_response_models"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_response_models CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_response_models();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_model_metadata_response>(global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_model_metadata_response.CreateFromDiscriminatorValue); } },
                { "model", n => { Model = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response>(global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_search_model_metadata_response>("metadata", Metadata);
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response>("model", Model);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
