// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Replicate.OpenApiClient.Models
{
    /// <summary>Whether the model is public or private</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SchemasModelResponseVisibility
    {
        [EnumMember(Value = "public")]
        #pragma warning disable CS1591
        PublicValue,
        #pragma warning restore CS1591
        [EnumMember(Value = "private")]
        #pragma warning disable CS1591
        PrivateValue,
        #pragma warning restore CS1591
    }
}
