// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Replicate.OpenApiClient.Models
{
    /// <summary>
    /// A file resource
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class Schemas_file_response : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A dictionary of checksums for the file keyed by the algorithm name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response_checksums? Checksums { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response_checksums Checksums { get; set; }
#endif
        /// <summary>The content / MIME type of the file</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentType { get; set; }
#nullable restore
#else
        public string ContentType { get; set; }
#endif
        /// <summary>When the file was created</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>When the file expires</summary>
        public DateTimeOffset? ExpiresAt { get; set; }
        /// <summary>A unique, randomly-generated identifier for the file resource</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Metadata provided by user when the file was created</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response_metadata? Metadata { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response_metadata Metadata { get; set; }
#endif
        /// <summary>The length of the file in bytes</summary>
        public int? Size { get; set; }
        /// <summary>A dictionary of URLs associated with the file resource</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response_urls? Urls { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response_urls Urls { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response"/> and sets the default values.
        /// </summary>
        public Schemas_file_response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "checksums", n => { Checksums = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response_checksums>(global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response_checksums.CreateFromDiscriminatorValue); } },
                { "content_type", n => { ContentType = n.GetStringValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "expires_at", n => { ExpiresAt = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "metadata", n => { Metadata = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response_metadata>(global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response_metadata.CreateFromDiscriminatorValue); } },
                { "size", n => { Size = n.GetIntValue(); } },
                { "urls", n => { Urls = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response_urls>(global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response_urls.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response_checksums>("checksums", Checksums);
            writer.WriteStringValue("content_type", ContentType);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteDateTimeOffsetValue("expires_at", ExpiresAt);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response_metadata>("metadata", Metadata);
            writer.WriteIntValue("size", Size);
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_file_response_urls>("urls", Urls);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
