// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Replicate.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Schemas_training_response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The time when the training completed</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>The time when the training was created</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Error message if the training failed</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>The unique ID of the training</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The input parameters used for the training</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_input? Input { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_input Input { get; set; }
#endif
        /// <summary>The logs from the training process</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Logs { get; set; }
#nullable restore
#else
        public string Logs { get; set; }
#endif
        /// <summary>Metrics about the training process</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_metrics? Metrics { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_metrics Metrics { get; set; }
#endif
        /// <summary>The name of the model in the format owner/name</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>The output of the training process</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_output? Output { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_output Output { get; set; }
#endif
        /// <summary>How the training was created</summary>
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_source? Source { get; set; }
        /// <summary>The time when the training started</summary>
        public DateTimeOffset? StartedAt { get; set; }
        /// <summary>The current status of the training. `canceled` means the training was canceled (either by the user or because it reached its deadline while running). `aborted` means the training was terminated before it started running (for example, when a deadline is reached before the training starts).</summary>
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_status? Status { get; set; }
        /// <summary>URLs for interacting with the training</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_urls? Urls { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_urls Urls { get; set; }
#endif
        /// <summary>The ID of the model version used for training</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response"/> and sets the default values.
        /// </summary>
        public Schemas_training_response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completed_at", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "input", n => { Input = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_input>(global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_input.CreateFromDiscriminatorValue); } },
                { "logs", n => { Logs = n.GetStringValue(); } },
                { "metrics", n => { Metrics = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_metrics>(global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_metrics.CreateFromDiscriminatorValue); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "output", n => { Output = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_output>(global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_output.CreateFromDiscriminatorValue); } },
                { "source", n => { Source = n.GetEnumValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_source>(); } },
                { "started_at", n => { StartedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_status>(); } },
                { "urls", n => { Urls = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_urls>(global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_urls.CreateFromDiscriminatorValue); } },
                { "version", n => { Version = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("completed_at", CompletedAt);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteStringValue("error", Error);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_input>("input", Input);
            writer.WriteStringValue("logs", Logs);
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_metrics>("metrics", Metrics);
            writer.WriteStringValue("model", Model);
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_output>("output", Output);
            writer.WriteEnumValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_source>("source", Source);
            writer.WriteDateTimeOffsetValue("started_at", StartedAt);
            writer.WriteEnumValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_status>("status", Status);
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_training_response_urls>("urls", Urls);
            writer.WriteStringValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
