// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Replicate.OpenApiClient.Models
{
    /// <summary>How the training was created</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Schemas_training_response_source
    {
        [EnumMember(Value = "web")]
        #pragma warning disable CS1591
        Web,
        #pragma warning restore CS1591
        [EnumMember(Value = "api")]
        #pragma warning disable CS1591
        Api,
        #pragma warning restore CS1591
    }
}
