// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Replicate.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class SchemasPredictionResponse : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The time that the model completed the prediction and all outputs were uploaded</summary>
        public DateTimeOffset? CompletedAt { get; set; }
        /// <summary>The time that the prediction was created</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>Whether the prediction output has been deleted</summary>
        public bool? DataRemoved { get; set; }
        /// <summary>The absolute time at which the prediction will be automatically canceled if it has not completed</summary>
        public DateTimeOffset? Deadline { get; set; }
        /// <summary>The name of the deployment that created the prediction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Deployment { get; set; }
#nullable restore
#else
        public string Deployment { get; set; }
#endif
        /// <summary>An error string if the model status is `&quot;failed&quot;`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Error { get; set; }
#nullable restore
#else
        public string Error { get; set; }
#endif
        /// <summary>The id property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The prediction input</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse_input? Input { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse_input Input { get; set; }
#endif
        /// <summary>The log output from the model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Logs { get; set; }
#nullable restore
#else
        public string Logs { get; set; }
#endif
        /// <summary>Additional metrics associated with the prediction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseMetrics? Metrics { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseMetrics Metrics { get; set; }
#endif
        /// <summary>The name of the model that created the prediction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Model { get; set; }
#nullable restore
#else
        public string Model { get; set; }
#endif
        /// <summary>The prediction output, which can be any JSON-serializable value, depending on the model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse_output? Output { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse_output Output { get; set; }
#endif
        /// <summary>Indicates how the prediction was created</summary>
        public global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse_source? Source { get; set; }
        /// <summary>The time that the model began the prediction</summary>
        public DateTimeOffset? StartedAt { get; set; }
        /// <summary>The prediction status. `canceled` means the prediction was canceled (either by the user or because it reached its deadline while running). `aborted` means the prediction was terminated before it started running (for example, when a deadline is reached before the prediction starts).</summary>
        public global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse_status? Status { get; set; }
        /// <summary>URLs for working with the prediction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseUrls? Urls { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseUrls Urls { get; set; }
#endif
        /// <summary>The version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.UnionBranch? Version { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.UnionBranch Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse"/> and sets the default values.
        /// </summary>
        public SchemasPredictionResponse()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "completed_at", n => { CompletedAt = n.GetDateTimeOffsetValue(); } },
                { "created_at", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "data_removed", n => { DataRemoved = n.GetBoolValue(); } },
                { "deadline", n => { Deadline = n.GetDateTimeOffsetValue(); } },
                { "deployment", n => { Deployment = n.GetStringValue(); } },
                { "error", n => { Error = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "input", n => { Input = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse_input>(global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse_input.CreateFromDiscriminatorValue); } },
                { "logs", n => { Logs = n.GetStringValue(); } },
                { "metrics", n => { Metrics = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseMetrics>(global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseMetrics.CreateFromDiscriminatorValue); } },
                { "model", n => { Model = n.GetStringValue(); } },
                { "output", n => { Output = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse_output>(global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse_output.CreateFromDiscriminatorValue); } },
                { "source", n => { Source = n.GetEnumValue<global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse_source>(); } },
                { "started_at", n => { StartedAt = n.GetDateTimeOffsetValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse_status>(); } },
                { "urls", n => { Urls = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseUrls>(global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseUrls.CreateFromDiscriminatorValue); } },
                { "version", n => { Version = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.UnionBranch>(global::Soenneker.Replicate.OpenApiClient.Models.UnionBranch.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("completed_at", CompletedAt);
            writer.WriteDateTimeOffsetValue("created_at", CreatedAt);
            writer.WriteBoolValue("data_removed", DataRemoved);
            writer.WriteDateTimeOffsetValue("deadline", Deadline);
            writer.WriteStringValue("deployment", Deployment);
            writer.WriteStringValue("error", Error);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse_input>("input", Input);
            writer.WriteStringValue("logs", Logs);
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseMetrics>("metrics", Metrics);
            writer.WriteStringValue("model", Model);
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse_output>("output", Output);
            writer.WriteEnumValue<global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse_source>("source", Source);
            writer.WriteDateTimeOffsetValue("started_at", StartedAt);
            writer.WriteEnumValue<global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponse_status>("status", Status);
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseUrls>("urls", Urls);
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.UnionBranch>("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
