// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Replicate.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Schemas_model_response : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>A URL for the model&apos;s cover image</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CoverImageUrl { get; set; }
#nullable restore
#else
        public string CoverImageUrl { get; set; }
#endif
        /// <summary>The model&apos;s default example prediction</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response_default_example? DefaultExample { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response_default_example DefaultExample { get; set; }
#endif
        /// <summary>A description of the model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>A URL for the model&apos;s source code on GitHub</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GithubUrl { get; set; }
#nullable restore
#else
        public string GithubUrl { get; set; }
#endif
        /// <summary>Boolean indicating whether the model is officially maintained by Replicate. Official models are always on, have stable API interfaces, and predictable pricing.</summary>
        public bool? IsOfficial { get; set; }
        /// <summary>The model&apos;s latest version</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response_latest_version? LatestVersion { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response_latest_version LatestVersion { get; set; }
#endif
        /// <summary>A URL for the model&apos;s license</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LicenseUrl { get; set; }
#nullable restore
#else
        public string LicenseUrl { get; set; }
#endif
        /// <summary>The name of the model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The name of the user or organization that owns the model</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Owner { get; set; }
#nullable restore
#else
        public string Owner { get; set; }
#endif
        /// <summary>A URL for the model&apos;s paper</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaperUrl { get; set; }
#nullable restore
#else
        public string PaperUrl { get; set; }
#endif
        /// <summary>The number of times the model has been run</summary>
        public int? RunCount { get; set; }
        /// <summary>The URL of the model on Replicate</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Url { get; set; }
#nullable restore
#else
        public string Url { get; set; }
#endif
        /// <summary>Whether the model is public or private</summary>
        public global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response_visibility? Visibility { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response"/> and sets the default values.
        /// </summary>
        public Schemas_model_response()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "cover_image_url", n => { CoverImageUrl = n.GetStringValue(); } },
                { "default_example", n => { DefaultExample = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response_default_example>(global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response_default_example.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "github_url", n => { GithubUrl = n.GetStringValue(); } },
                { "is_official", n => { IsOfficial = n.GetBoolValue(); } },
                { "latest_version", n => { LatestVersion = n.GetObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response_latest_version>(global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response_latest_version.CreateFromDiscriminatorValue); } },
                { "license_url", n => { LicenseUrl = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "owner", n => { Owner = n.GetStringValue(); } },
                { "paper_url", n => { PaperUrl = n.GetStringValue(); } },
                { "run_count", n => { RunCount = n.GetIntValue(); } },
                { "url", n => { Url = n.GetStringValue(); } },
                { "visibility", n => { Visibility = n.GetEnumValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response_visibility>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("cover_image_url", CoverImageUrl);
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response_default_example>("default_example", DefaultExample);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("github_url", GithubUrl);
            writer.WriteBoolValue("is_official", IsOfficial);
            writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response_latest_version>("latest_version", LatestVersion);
            writer.WriteStringValue("license_url", LicenseUrl);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("owner", Owner);
            writer.WriteStringValue("paper_url", PaperUrl);
            writer.WriteIntValue("run_count", RunCount);
            writer.WriteStringValue("url", Url);
            writer.WriteEnumValue<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_model_response_visibility>("visibility", Visibility);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
