// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Replicate.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseVersionBranch1"/>, <see cref="global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseVersionWrapper"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SchemasPredictionResponseVersion : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseVersionBranch1"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseVersionBranch1? SchemasPredictionResponseVersionBranch1 { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseVersionBranch1 SchemasPredictionResponseVersionBranch1 { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseVersionWrapper"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseVersionWrapper? SchemasPredictionResponseVersionWrapper { get; set; }
#nullable restore
#else
        public global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseVersionWrapper SchemasPredictionResponseVersionWrapper { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseVersion"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseVersion CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("")?.GetStringValue();
            var result = new global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseVersion();
            if("SchemasPredictionResponseVersionBranch1".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SchemasPredictionResponseVersionBranch1 = new global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseVersionBranch1();
            }
            else if("SchemasPredictionResponseVersionWrapper".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.SchemasPredictionResponseVersionWrapper = new global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseVersionWrapper();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(SchemasPredictionResponseVersionBranch1 != null)
            {
                return SchemasPredictionResponseVersionBranch1.GetFieldDeserializers();
            }
            else if(SchemasPredictionResponseVersionWrapper != null)
            {
                return SchemasPredictionResponseVersionWrapper.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(SchemasPredictionResponseVersionBranch1 != null)
            {
                writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseVersionBranch1>(null, SchemasPredictionResponseVersionBranch1);
            }
            else if(SchemasPredictionResponseVersionWrapper != null)
            {
                writer.WriteObjectValue<global::Soenneker.Replicate.OpenApiClient.Models.SchemasPredictionResponseVersionWrapper>(null, SchemasPredictionResponseVersionWrapper);
            }
        }
    }
}
#pragma warning restore CS0618
