// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Replicate.OpenApiClient.Models;
using Soenneker.Replicate.OpenApiClient.ModelsRequests.Item.Item.Versions.Item.Trainings;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Replicate.OpenApiClient.ModelsRequests.Item.Item.Versions.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \models\{model_owner}\{model_name}\versions\{version_id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithVersion_ItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The trainings property</summary>
        public global::Soenneker.Replicate.OpenApiClient.ModelsRequests.Item.Item.Versions.Item.Trainings.TrainingsRequestBuilder Trainings
        {
            get => new global::Soenneker.Replicate.OpenApiClient.ModelsRequests.Item.Item.Versions.Item.Trainings.TrainingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.ModelsRequests.Item.Item.Versions.Item.WithVersion_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithVersion_ItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/models/{model_owner}/{model_name}/versions/{version_id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Replicate.OpenApiClient.ModelsRequests.Item.Item.Versions.Item.WithVersion_ItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithVersion_ItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/models/{model_owner}/{model_name}/versions/{version_id}", rawUrl)
        {
        }
        /// <summary>
        /// Delete a model version and all associated predictions, including all output files.Model version deletion has some restrictions:- You can only delete versions from models you own.- You can only delete versions from private models.- You cannot delete a version if someone other than you has run predictions with it.- You cannot delete a version if it is being used as the base model for a fine tune/training.- You cannot delete a version if it has an associated deployment.- You cannot delete a version if another model version is overridden to use it.Example cURL request:```commandcurl -s -X DELETE \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  https://api.replicate.com/v1/models/replicate/hello-world/versions/5c7d5dc6dd8bf75c1acaa8565735e7986bc5b66206b55cca93cb72c9bf15ccaa```The response will be an empty 202, indicating the deletion request has been accepted. It might take a few minutes to be processed.
        /// </summary>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            await RequestAdapter.SendNoContentAsync(requestInfo, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Example cURL request:```consolecurl -s \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  https://api.replicate.com/v1/models/replicate/hello-world/versions/5c7d5dc6dd8bf75c1acaa8565735e7986bc5b66206b55cca93cb72c9bf15ccaa```The response will be the version object:```json{  &quot;id&quot;: &quot;5c7d5dc6dd8bf75c1acaa8565735e7986bc5b66206b55cca93cb72c9bf15ccaa&quot;,  &quot;created_at&quot;: &quot;2022-04-26T19:29:04.418669Z&quot;,  &quot;cog_version&quot;: &quot;0.3.0&quot;,  &quot;openapi_schema&quot;: {...}}```Every model describes its inputs and outputs with [OpenAPI Schema Objects](https://spec.openapis.org/oas/latest.html#schemaObject) in the `openapi_schema` property.The `openapi_schema.components.schemas.Input` property for the [replicate/hello-world](https://replicate.com/replicate/hello-world) model looks like this:```json{  &quot;type&quot;: &quot;object&quot;,  &quot;title&quot;: &quot;Input&quot;,  &quot;required&quot;: [    &quot;text&quot;  ],  &quot;properties&quot;: {    &quot;text&quot;: {      &quot;x-order&quot;: 0,      &quot;type&quot;: &quot;string&quot;,      &quot;title&quot;: &quot;Text&quot;,      &quot;description&quot;: &quot;Text to prefix with &apos;hello &apos;&quot;    }  }}```The `openapi_schema.components.schemas.Output` property for the [replicate/hello-world](https://replicate.com/replicate/hello-world) model looks like this:```json{  &quot;type&quot;: &quot;string&quot;,  &quot;title&quot;: &quot;Output&quot;}```For more details, see the docs on [Cog&apos;s supported input and output types](https://github.com/replicate/cog/blob/75b7802219e7cd4cee845e34c4c22139558615d4/docs/python.md#input-and-output-types)
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.Models.Schemas_version_response"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_version_response?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_version_response> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            return await RequestAdapter.SendAsync<global::Soenneker.Replicate.OpenApiClient.Models.Schemas_version_response>(requestInfo, global::Soenneker.Replicate.OpenApiClient.Models.Schemas_version_response.CreateFromDiscriminatorValue, default, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Delete a model version and all associated predictions, including all output files.Model version deletion has some restrictions:- You can only delete versions from models you own.- You can only delete versions from private models.- You cannot delete a version if someone other than you has run predictions with it.- You cannot delete a version if it is being used as the base model for a fine tune/training.- You cannot delete a version if it has an associated deployment.- You cannot delete a version if another model version is overridden to use it.Example cURL request:```commandcurl -s -X DELETE \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  https://api.replicate.com/v1/models/replicate/hello-world/versions/5c7d5dc6dd8bf75c1acaa8565735e7986bc5b66206b55cca93cb72c9bf15ccaa```The response will be an empty 202, indicating the deletion request has been accepted. It might take a few minutes to be processed.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            return requestInfo;
        }
        /// <summary>
        /// Example cURL request:```consolecurl -s \  -H &quot;Authorization: Bearer $REPLICATE_API_TOKEN&quot; \  https://api.replicate.com/v1/models/replicate/hello-world/versions/5c7d5dc6dd8bf75c1acaa8565735e7986bc5b66206b55cca93cb72c9bf15ccaa```The response will be the version object:```json{  &quot;id&quot;: &quot;5c7d5dc6dd8bf75c1acaa8565735e7986bc5b66206b55cca93cb72c9bf15ccaa&quot;,  &quot;created_at&quot;: &quot;2022-04-26T19:29:04.418669Z&quot;,  &quot;cog_version&quot;: &quot;0.3.0&quot;,  &quot;openapi_schema&quot;: {...}}```Every model describes its inputs and outputs with [OpenAPI Schema Objects](https://spec.openapis.org/oas/latest.html#schemaObject) in the `openapi_schema` property.The `openapi_schema.components.schemas.Input` property for the [replicate/hello-world](https://replicate.com/replicate/hello-world) model looks like this:```json{  &quot;type&quot;: &quot;object&quot;,  &quot;title&quot;: &quot;Input&quot;,  &quot;required&quot;: [    &quot;text&quot;  ],  &quot;properties&quot;: {    &quot;text&quot;: {      &quot;x-order&quot;: 0,      &quot;type&quot;: &quot;string&quot;,      &quot;title&quot;: &quot;Text&quot;,      &quot;description&quot;: &quot;Text to prefix with &apos;hello &apos;&quot;    }  }}```The `openapi_schema.components.schemas.Output` property for the [replicate/hello-world](https://replicate.com/replicate/hello-world) model looks like this:```json{  &quot;type&quot;: &quot;string&quot;,  &quot;title&quot;: &quot;Output&quot;}```For more details, see the docs on [Cog&apos;s supported input and output types](https://github.com/replicate/cog/blob/75b7802219e7cd4cee845e34c4c22139558615d4/docs/python.md#input-and-output-types)
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Replicate.OpenApiClient.ModelsRequests.Item.Item.Versions.Item.WithVersion_ItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Replicate.OpenApiClient.ModelsRequests.Item.Item.Versions.Item.WithVersion_ItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Replicate.OpenApiClient.ModelsRequests.Item.Item.Versions.Item.WithVersion_ItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
